# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(blank=True, max_length=25)),
                ('food', models.CharField(blank=True, max_length=25)),
                ('enviornmetal', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=25)),
                ('last_name', models.CharField(blank=True, max_length=25)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('transgender', 'transgender')], default='female', max_length=12)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=25)),
                ('known_allergies', models.ManyToManyField(blank=True, to='patients.Allergy')),
            ],
        ),
    ]
